### ISSUE TITLE
Not Loading up Plugin

### ISSUE THREAD

**Issue by ZK-12** [jacquesCedric/WUPS_dark_mode_plugin#2]
When loading up Plugin it Patchs it but Dark Mode does not work altogether.  I Have tried So Many Times and It Still Does not work. Please Try to Fix Plugin

by Zeldaking_123

**Comment by unresolvedsymbol** [comment]
I attempted to fix this, I got it to work first try by setting the memory addresses with an app change foreground hook to the home menu TID but it doesn't seem to stay changed after starting/closing another app. I'd say just put BullyWiiPlaza's gecko code on the SD and load it with SDGeckiine. Not any more trivial than starting WUPSPluginLoader anyway.

**Comment by ZK-12** [comment]
> I'd say just put BullyWiiPlaza's gecko code on the SD and load it with SDGeckiine.

Is there a Video or anything to help this or nah
